init: swagger.yml
swagger.yml:
	swagger init spec \
	--title "Capacity protocol" \
	--description "Capacity protocol" \
	--version 0.0.1 \
	--scheme http \
	--produces application/house.rosskeen.capacity.v1+json

validate: swagger.yml
	swagger validate swagger.yml
